import { describe, expect, test } from 'bun:test'
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

import { generateMigrationArtifacts } from '../index'

async function withTempDir(fn: (dir: string) => Promise<void>): Promise<void> {
  const dir = await mkdtemp(join(tmpdir(), 'chkit-codegen-migrations-'))
  try {
    await fn(dir)
  } finally {
    await rm(dir, { recursive: true, force: true })
  }
}

describe('generateMigrationArtifacts', () => {
  test('generates a valid module with one migration', async () => {
    await withTempDir(async (dir) => {
      const migrationsDir = join(dir, 'migrations')
      await mkdir(migrationsDir)
      await writeFile(
        join(migrationsDir, '20260325114021_init.sql'),
        'CREATE TABLE IF NOT EXISTS app.users (id UInt64) ENGINE = MergeTree() ORDER BY id;',
        'utf8'
      )

      const result = await generateMigrationArtifacts({
        migrationsDir,
        toolVersion: '0.1.0',
      })

      expect(result.migrationCount).toBe(1)
      expect(result.content).toContain('// This file is auto-generated by chkit codegen')
      expect(result.content).toContain('// chkit-codegen-version: 0.1.0')
      expect(result.content).toContain('export interface MigrationEntry {')
      expect(result.content).toContain('export interface MigrationExecutor {')
      expect(result.content).toContain("name: '20260325114021_init',")
      expect(result.content).toContain('CREATE TABLE IF NOT EXISTS app.users')
      expect(result.content).toContain('export const migrations: MigrationEntry[]')
      expect(result.content).toContain('function splitSqlStatements(')
      expect(result.content).toContain('function extractExecutableStatements(')
      expect(result.content).toContain('export async function runMigrations(')
      expect(result.content).toContain('_chkit_migrations')
      expect(result.content).toContain('executor: MigrationExecutor')
      expect(result.content.endsWith('\n')).toBe(true)
    })
  })

  test('multiple migrations are sorted alphabetically', async () => {
    await withTempDir(async (dir) => {
      const migrationsDir = join(dir, 'migrations')
      await mkdir(migrationsDir)
      await writeFile(
        join(migrationsDir, '20260326_second.sql'),
        'CREATE TABLE app.events (id UInt64) ENGINE = MergeTree() ORDER BY id;',
        'utf8'
      )
      await writeFile(
        join(migrationsDir, '20260325_first.sql'),
        'CREATE TABLE app.users (id UInt64) ENGINE = MergeTree() ORDER BY id;',
        'utf8'
      )

      const result = await generateMigrationArtifacts({ migrationsDir })

      expect(result.migrationCount).toBe(2)
      const firstIndex = result.content.indexOf("name: '20260325_first'")
      const secondIndex = result.content.indexOf("name: '20260326_second'")
      expect(firstIndex).toBeGreaterThan(-1)
      expect(secondIndex).toBeGreaterThan(-1)
      expect(firstIndex).toBeLessThan(secondIndex)
    })
  })

  test('empty migrations directory produces valid module with empty array', async () => {
    await withTempDir(async (dir) => {
      const migrationsDir = join(dir, 'migrations')
      await mkdir(migrationsDir)

      const result = await generateMigrationArtifacts({ migrationsDir })

      expect(result.migrationCount).toBe(0)
      expect(result.content).toContain('export const migrations: MigrationEntry[] = []')
      expect(result.content).toContain('export interface MigrationEntry {')
      expect(result.content).toContain('export async function runMigrations(')
    })
  })

  test('backticks in SQL are escaped in template literals', async () => {
    await withTempDir(async (dir) => {
      const migrationsDir = join(dir, 'migrations')
      await mkdir(migrationsDir)
      await writeFile(
        join(migrationsDir, '20260325_backticks.sql'),
        'CREATE TABLE app.users (`id` UInt64, `name` String) ENGINE = MergeTree() ORDER BY `id`;',
        'utf8'
      )

      const result = await generateMigrationArtifacts({ migrationsDir })

      expect(result.migrationCount).toBe(1)
      // Backticks should be escaped in the template literal
      expect(result.content).toContain('\\`id\\`')
      expect(result.content).toContain('\\`name\\`')
      // Should not contain unescaped backticks in the SQL content
      expect(result.content).not.toContain('(`id`')
    })
  })

  test('journal table creation and migration tracking logic is present', async () => {
    await withTempDir(async (dir) => {
      const migrationsDir = join(dir, 'migrations')
      await mkdir(migrationsDir)

      const result = await generateMigrationArtifacts({ migrationsDir })

      expect(result.content).toContain('CREATE TABLE IF NOT EXISTS')
      expect(result.content).toContain('_chkit_migrations')
      expect(result.content).toContain('journalTable')
      expect(result.content).toContain('SELECT name FROM')
      expect(result.content).toContain('INSERT INTO')
      expect(result.content).toContain('applied_at')
      expect(result.content).toContain('checksum')
      expect(result.content).toContain('chkit_version')
      expect(result.content).toContain("Promise<{ applied: string[]; skipped: string[] }>")
    })
  })

  test('nonexistent migrations directory produces empty array', async () => {
    await withTempDir(async (dir) => {
      const migrationsDir = join(dir, 'does-not-exist')

      const result = await generateMigrationArtifacts({ migrationsDir })

      expect(result.migrationCount).toBe(0)
      expect(result.content).toContain('export const migrations: MigrationEntry[] = []')
    })
  })

  test('ignores non-.sql files in migrations directory', async () => {
    await withTempDir(async (dir) => {
      const migrationsDir = join(dir, 'migrations')
      await mkdir(migrationsDir)
      await writeFile(join(migrationsDir, '20260325_init.sql'), 'CREATE TABLE app.t (id UInt64) ENGINE = MergeTree() ORDER BY id;', 'utf8')
      await writeFile(join(migrationsDir, 'README.md'), '# Migrations', 'utf8')
      await writeFile(join(migrationsDir, '.gitkeep'), '', 'utf8')

      const result = await generateMigrationArtifacts({ migrationsDir })

      expect(result.migrationCount).toBe(1)
      expect(result.content).toContain("name: '20260325_init'")
      expect(result.content).not.toContain('README')
      expect(result.content).not.toContain('gitkeep')
    })
  })

  test('dollar braces in SQL are escaped', async () => {
    await withTempDir(async (dir) => {
      const migrationsDir = join(dir, 'migrations')
      await mkdir(migrationsDir)
      await writeFile(
        join(migrationsDir, '20260325_dollar.sql'),
        "SELECT '${not_a_var}' FROM system.one;",
        'utf8'
      )

      const result = await generateMigrationArtifacts({ migrationsDir })

      // ${not_a_var} should be escaped so it's not treated as template interpolation
      expect(result.content).toContain('\\${not_a_var}')
    })
  })
})
