import type { TableDefinition } from '@chkit/core'

export function renderHeader(toolVersion: string): string[] {
  const lines = [
    '// This file is auto-generated by chkit codegen — do not edit manually.',
  ]
  lines.push(`// chkit-codegen-version: ${toolVersion}`)
  return lines
}

/** Preserve existing names for ordinary tables; special columns need an insert shape. */
export function insertTypeName(table: TableDefinition, rowType: string): string {
  return table.columns.some((column) => column.defaultKind && column.defaultKind !== 'DEFAULT')
    ? `${rowType}Insert`
    : rowType
}
