export function renderHeader(toolVersion: string): string[] {
  const lines = [
    '// This file is auto-generated by chkit codegen — do not edit manually.',
  ]
  lines.push(`// chkit-codegen-version: ${toolVersion}`)
  return lines
}
