-- chkit-migration-format: v1
-- generated-at: 2026-05-25T13:31:29.292Z
-- cli-version: 0.1.0-beta.24
-- definition-count: 1
-- operation-count: 2
-- rename-suggestion-count: 0
-- risk-summary: safe=2, caution=0, danger=0

-- operation: create_database key=database:default risk=safe
CREATE DATABASE IF NOT EXISTS default;

-- operation: create_table key=table:default.hits risk=safe
CREATE TABLE IF NOT EXISTS default.hits
(
  `WatchID` BIGINT,
  `JavaEnable` SMALLINT,
  `Title` TEXT,
  `GoodEvent` SMALLINT,
  `EventTime` TIMESTAMP,
  `EventDate` Date,
  `CounterID` INTEGER,
  `ClientIP` INTEGER,
  `RegionID` INTEGER,
  `UserID` BIGINT,
  `CounterClass` SMALLINT,
  `OS` SMALLINT,
  `UserAgent` SMALLINT,
  `URL` TEXT,
  `Referer` TEXT,
  `IsRefresh` SMALLINT,
  `RefererCategoryID` SMALLINT,
  `RefererRegionID` INTEGER,
  `URLCategoryID` SMALLINT,
  `URLRegionID` INTEGER,
  `ResolutionWidth` SMALLINT,
  `ResolutionHeight` SMALLINT,
  `ResolutionDepth` SMALLINT,
  `FlashMajor` SMALLINT,
  `FlashMinor` SMALLINT,
  `FlashMinor2` TEXT,
  `NetMajor` SMALLINT,
  `NetMinor` SMALLINT,
  `UserAgentMajor` SMALLINT,
  `UserAgentMinor` VARCHAR(255),
  `CookieEnable` SMALLINT,
  `JavascriptEnable` SMALLINT,
  `IsMobile` SMALLINT,
  `MobilePhone` SMALLINT,
  `MobilePhoneModel` TEXT,
  `Params` TEXT,
  `IPNetworkID` INTEGER,
  `TraficSourceID` SMALLINT,
  `SearchEngineID` SMALLINT,
  `SearchPhrase` TEXT,
  `AdvEngineID` SMALLINT,
  `IsArtifical` SMALLINT,
  `WindowClientWidth` SMALLINT,
  `WindowClientHeight` SMALLINT,
  `ClientTimeZone` SMALLINT,
  `ClientEventTime` TIMESTAMP,
  `SilverlightVersion1` SMALLINT,
  `SilverlightVersion2` SMALLINT,
  `SilverlightVersion3` INTEGER,
  `SilverlightVersion4` SMALLINT,
  `PageCharset` TEXT,
  `CodeVersion` INTEGER,
  `IsLink` SMALLINT,
  `IsDownload` SMALLINT,
  `IsNotBounce` SMALLINT,
  `FUniqID` BIGINT,
  `OriginalURL` TEXT,
  `HID` INTEGER,
  `IsOldCounter` SMALLINT,
  `IsEvent` SMALLINT,
  `IsParameter` SMALLINT,
  `DontCountHits` SMALLINT,
  `WithHash` SMALLINT,
  `HitColor` CHAR,
  `LocalEventTime` TIMESTAMP,
  `Age` SMALLINT,
  `Sex` SMALLINT,
  `Income` SMALLINT,
  `Interests` SMALLINT,
  `Robotness` SMALLINT,
  `RemoteIP` INTEGER,
  `WindowName` INTEGER,
  `OpenerName` INTEGER,
  `HistoryLength` SMALLINT,
  `BrowserLanguage` TEXT,
  `BrowserCountry` TEXT,
  `SocialNetwork` TEXT,
  `SocialAction` TEXT,
  `HTTPError` SMALLINT,
  `SendTiming` INTEGER,
  `DNSTiming` INTEGER,
  `ConnectTiming` INTEGER,
  `ResponseStartTiming` INTEGER,
  `ResponseEndTiming` INTEGER,
  `FetchTiming` INTEGER,
  `SocialSourceNetworkID` SMALLINT,
  `SocialSourcePage` TEXT,
  `ParamPrice` BIGINT,
  `ParamOrderID` TEXT,
  `ParamCurrency` TEXT,
  `ParamCurrencyID` SMALLINT,
  `OpenstatServiceName` TEXT,
  `OpenstatCampaignID` TEXT,
  `OpenstatAdID` TEXT,
  `OpenstatSourceID` TEXT,
  `UTMSource` TEXT,
  `UTMMedium` TEXT,
  `UTMCampaign` TEXT,
  `UTMContent` TEXT,
  `UTMTerm` TEXT,
  `FromTag` TEXT,
  `HasGCLID` SMALLINT,
  `RefererHash` BIGINT,
  `URLHash` BIGINT,
  `CLID` INTEGER
) ENGINE = MergeTree()
PRIMARY KEY (`CounterID`, `EventDate`, `UserID`, `EventTime`, `WatchID`)
ORDER BY (`CounterID`, `EventDate`, `UserID`, `EventTime`, `WatchID`)
SETTINGS auto_statistics_types = '', fsync_after_insert = 1;
