"""`chkit init` — scaffold a starter project.

1:1 port of ``packages/cli/src/commands/init.ts``. Writes
``clickhouse.config.py`` and ``src/db/schema/example.py`` into the
current working directory if they don't exist. Then, unless ``--yes``
is passed, tries to dispatch the optional ObsessionDB onboarding flow.
If the obsessiondb plugin isn't installed, degrades to the static
"Next steps" runbook (same as the TS version).

Onboarding contract: the ObsessionDB plugin must be importable as
``chkit_plugin_obsessiondb`` and expose ``run_onboarding(config_path,
connect, email, code, org_name)``. Missing-plugin is silent; any other
import or runtime error surfaces.
"""

from __future__ import annotations

import importlib
import os
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Protocol

import typer

DEFAULT_CONFIG_FILE = "clickhouse.config.py"

OBSESSIONDB_PLUGIN_MODULE = "chkit_plugin_obsessiondb"


class ConnectChoice(StrEnum):
    claim = "claim"
    account = "account"
    clickhouse = "clickhouse"
    later = "later"


class _OnboardingModule(Protocol):
    def run_onboarding(
        self,
        *,
        config_path: Path,
        connect: ConnectChoice | None,
        email: str | None,
        code: str | None,
        org_name: str | None,
    ) -> None: ...


_CONFIG_TEMPLATE = '''"""chkit / ClickHouse configuration. Generated by `chkit init`."""

import os

from chkit import define_config

config = define_config(
    {
        "schema": "./src/db/schema/**/*.py",
        "outDir": "./chkit",
        "migrationsDir": "./chkit/migrations",
        "metaDir": "./chkit/meta",
        "plugins": [
            # Register plugins inline. Example:
            # from chkit_plugin_codegen import codegen
            # codegen(emit_zod=True),
        ],
        "clickhouse": {
            "url": os.environ.get("CLICKHOUSE_URL", "http://localhost:8123"),
            "username": os.environ.get("CLICKHOUSE_USER", "default"),
            "password": os.environ.get("CLICKHOUSE_PASSWORD", ""),
            "database": os.environ.get("CLICKHOUSE_DB", "default"),
        },
    }
)
'''


_EXAMPLE_TEMPLATE = '''"""Example chkit schema."""

from chkit import schema, table

events = table(
    database="default",
    name="events",
    engine="MergeTree",
    columns=[
        {"name": "id", "type": "UInt64"},
        {"name": "source", "type": "String"},
        {"name": "ingested_at", "type": "DateTime64(3)", "default": "fn:now64(3)"},
    ],
    primaryKey=["id"],
    orderBy=["id"],
    partitionBy="toYYYYMM(ingested_at)",
)

definitions = schema(events)
'''


def _write_if_missing(path: Path, content: str) -> bool:
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _try_import_obsessiondb() -> _OnboardingModule | None:
    """Import the obsessiondb plugin; return None only when genuinely absent.

    Any other import or runtime error inside the plugin must surface — not
    every ImportError counts as "plugin not installed". We only swallow the
    case where the top-level package itself is missing.
    """
    try:
        module = importlib.import_module(OBSESSIONDB_PLUGIN_MODULE)
    except ModuleNotFoundError as error:
        if error.name == OBSESSIONDB_PLUGIN_MODULE:
            return None
        raise
    return module


def _maybe_run_onboarding(
    config_path: Path,
    *,
    yes: bool,
    connect: ConnectChoice | None,
    email: str | None,
    code: str | None,
    org_name: str | None,
) -> bool:
    """Run ObsessionDB onboarding if appropriate. Returns True if it ran."""
    if yes:
        return False
    module = _try_import_obsessiondb()
    if module is None:
        return False
    module.run_onboarding(
        config_path=config_path,
        connect=connect,
        email=email,
        code=code,
        org_name=org_name,
    )
    return True


def _print_next_steps() -> None:
    typer.echo("")
    typer.echo("Next steps:")
    typer.echo(
        "  1. Set CLICKHOUSE_URL "
        "(and CLICKHOUSE_USER / CLICKHOUSE_PASSWORD / CLICKHOUSE_DB if needed)."
    )
    typer.echo("  2. Edit src/db/schema/example.py to match your data.")
    typer.echo("  3. Run: chkit generate --name init")
    typer.echo("  4. Run: chkit migrate --apply")
    typer.echo("")
    typer.echo(
        "Docs: https://chkit.obsessiondb.com/getting-started/add-to-existing-project/"
    )


def run(
    yes: Annotated[
        bool,
        typer.Option(
            "--yes",
            "-y",
            help="Skip interactive onboarding (silent file-writer mode for CI/scripts).",
        ),
    ] = False,
    connect: Annotated[
        ConnectChoice | None,
        typer.Option(
            "--connect",
            help="Pre-select the ObsessionDB connect choice (claim, account, clickhouse, later).",
        ),
    ] = None,
    email: Annotated[
        str | None,
        typer.Option("--email", help="Email for the ObsessionDB OTP signup flow."),
    ] = None,
    code: Annotated[
        str | None,
        typer.Option(
            "--code",
            help="OTP verification code for ObsessionDB signup (scriptable).",
        ),
    ] = None,
    org_name: Annotated[
        str | None,
        typer.Option(
            "--org-name", help="Override the auto-derived ObsessionDB organization name."
        ),
    ] = None,
) -> None:
    cwd = Path.cwd()
    config_path = cwd / DEFAULT_CONFIG_FILE
    schema_path = cwd / "src" / "db" / "schema" / "example.py"

    wrote_config = _write_if_missing(config_path, _CONFIG_TEMPLATE)
    wrote_schema = _write_if_missing(schema_path, _EXAMPLE_TEMPLATE)

    if wrote_config:
        typer.echo(f"Created {os.path.relpath(config_path, cwd)}")
    if wrote_schema:
        typer.echo(f"Created {os.path.relpath(schema_path, cwd)}")

    if _maybe_run_onboarding(
        config_path,
        yes=yes,
        connect=connect,
        email=email,
        code=code,
        org_name=org_name,
    ):
        return

    if wrote_config or wrote_schema:
        _print_next_steps()
