"""`chkit init` — scaffold a starter project.

1:1 port of ``packages/cli/src/commands/init.ts``. Writes ``clickhouse.config.py``
and ``src/db/schema/example.py`` into the current working directory if they
don't exist, then prints the same next-steps message as the TS version.
"""

from __future__ import annotations

import os
from pathlib import Path

import typer

DEFAULT_CONFIG_FILE = "clickhouse.config.py"


_CONFIG_TEMPLATE = '''"""chkit / ClickHouse configuration. Generated by `chkit init`."""

import os

from chkit import define_config

config = define_config(
    {
        "schema": "./src/db/schema/**/*.py",
        "outDir": "./chkit",
        "migrationsDir": "./chkit/migrations",
        "metaDir": "./chkit/meta",
        "plugins": [
            # Register plugins inline. Example:
            # from chkit_plugin_codegen import codegen
            # codegen(emit_zod=True),
        ],
        "clickhouse": {
            "url": os.environ.get("CLICKHOUSE_URL", "http://localhost:8123"),
            "username": os.environ.get("CLICKHOUSE_USER", "default"),
            "password": os.environ.get("CLICKHOUSE_PASSWORD", ""),
            "database": os.environ.get("CLICKHOUSE_DB", "default"),
        },
    }
)
'''


_EXAMPLE_TEMPLATE = '''"""Example chkit schema."""

from chkit import schema, table

events = table(
    database="default",
    name="events",
    engine="MergeTree",
    columns=[
        {"name": "id", "type": "UInt64"},
        {"name": "source", "type": "String"},
        {"name": "ingested_at", "type": "DateTime64(3)", "default": "fn:now64(3)"},
    ],
    primaryKey=["id"],
    orderBy=["id"],
    partitionBy="toYYYYMM(ingested_at)",
)

definitions = schema(events)
'''


def _write_if_missing(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` only if the file does not exist.

    Returns True if the file was written, False if it already existed.
    Matches the TypeScript ``writeIfMissing`` helper's silent-skip behavior.
    """
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def run() -> None:
    cwd = Path.cwd()
    config_path = cwd / DEFAULT_CONFIG_FILE
    schema_path = cwd / "src" / "db" / "schema" / "example.py"

    wrote_config = _write_if_missing(config_path, _CONFIG_TEMPLATE)
    wrote_schema = _write_if_missing(schema_path, _EXAMPLE_TEMPLATE)

    if wrote_config:
        typer.echo(f"Created {os.path.relpath(config_path, cwd)}")
    if wrote_schema:
        typer.echo(f"Created {os.path.relpath(schema_path, cwd)}")

    if wrote_config or wrote_schema:
        typer.echo("")
        typer.echo("Next steps:")
        typer.echo(
            "  1. Set CLICKHOUSE_URL "
            "(and CLICKHOUSE_USER / CLICKHOUSE_PASSWORD / CLICKHOUSE_DB if needed)."
        )
        typer.echo("  2. Edit src/db/schema/example.py to match your data.")
        typer.echo("  3. Run: chkit generate --name init")
        typer.echo("  4. Run: chkit migrate --apply")
        typer.echo("")
        typer.echo(
            "Docs: https://chkit.obsessiondb.com/getting-started/add-to-existing-project/"
        )
